package game.kontur.prototype;

import org.junit.jupiter.api.*;
import java.io.*;
import java.nio.file.*;
import java.util.*;
import java.util.stream.*;
import game.kontur.prototype.domain.*;
import game.kontur.prototype.domain.EpisodeModels.*;
import game.kontur.prototype.episode.*;
import static game.kontur.prototype.domain.GameTypes.*;
import static org.assertj.core.api.Assertions.*;

class AcidFrontVerificationTest {
 private static final Path REPORTS=Path.of("build/reports/kontur-v03");
 record PathRun(EpisodeSessionState session,EpisodeResult result){}
 static final class FixedDice implements DiceRoller {private final int a,b;FixedDice(int a,int b){this.a=a;this.b=b;}public RiskCheck roll(long seed,int used,int mod){int t=a+b+mod;return new RiskCheck(a,b,mod,t,t<=6?ReturnWindow.SHORT:t<=9?ReturnWindow.NORMAL:ReturnWindow.LONG);}}

 @Test void domainValidationAndImmutability(){assertThatThrownBy(()->Doctrine.of(OrderCard.M,OrderCard.M,OrderCard.R)).isInstanceOf(IllegalArgumentException.class);assertThat(Doctrine.all()).hasSize(6).extracting(Object::toString).containsExactly("M>A>R","M>R>A","A>M>R","A>R>M","R>M>A","R>A>M");var s=WorldState.initial();assertThatThrownBy(()->s.flags().add(WorldFlag.GREENHOUSE_ACTIVE)).isInstanceOf(UnsupportedOperationException.class);assertThatThrownBy(()->new EpisodeModels.DiceRoll(0,6)).isInstanceOf(IllegalArgumentException.class);}

 @Test void initialStateExactlyMatchesSpecification(){var w=WorldState.initial();assertThat(w).isEqualTo(new WorldState(1,43,FoodStatus.FOUR_DAYS,48,PowerMode.FULL,WorkshopStatus.ONLINE,2,ReactorCondition.NONE,ReactorLocation.NONE,ReactorOutput.NONE,Node12Relation.UNKNOWN,new MachineStates.KrotState(MachineLife.OPERATIONAL,MachineLocation.IN_FIELD,KrotActuator.WORN),new MachineStates.StrizhState(MachineLife.OPERATIONAL,MachineLocation.IN_FIELD,StrizhSensor.OPERATIONAL),new MachineStates.IglaState(MachineLife.OPERATIONAL,MachineLocation.IN_FIELD,IglaManipulator.OPERATIONAL),Set.of(),Set.of(),null,null,null,null));}

 @Test void fullVerificationAndReports() throws IOException {
  var runs=allRuns();assertThat(runs).hasSize(726);
  assertThat(runs).allSatisfy(r->{var s=r.session();var w=r.result().finalState();assertThat(s.decisions()).hasSize(5);assertThat(s.stage()).isEqualTo(EpisodeStage.EPILOGUE);assertThat(w.generatorHours()).isNotNegative();assertThat(w.spareParts()).isNotNegative();assertThat(s.events().stream().filter(e->e.stage()==EpisodeStage.NODE12_CONTACT)).hasSize(1);assertThat(r.result().events()).doesNotContainNull();});
  assertThat(runs.stream().map(r->r.result().profile()).collect(Collectors.toSet())).containsExactlyInAnyOrder(ShelterProfile.values());
  assertThat(runs.stream().collect(Collectors.groupingBy(r->r.result().profile(),()->new EnumMap<>(ShelterProfile.class),Collectors.counting()))).containsExactlyInAnyOrderEntriesOf(Map.of(ShelterProfile.AGRARIAN_ALLIANCE,65L,ShelterProfile.INDUSTRIAL_HUB,30L,ShelterProfile.POWERED_STRONGHOLD,54L,ShelterProfile.MOBILE_COMMUNE,113L,ShelterProfile.DEPENDENT_NETWORK,254L,ShelterProfile.AUSTERITY_ENCLAVE,174L,ShelterProfile.SURVIVAL_OUTPOST,36L));
  assertThat(runs.stream().map(r->r.result().finalState().contactTiming()).collect(Collectors.toSet())).containsExactlyInAnyOrder(ContactTiming.EARLY,ContactTiming.LATE);
  assertThat(runs.stream().filter(r->r.result().finalState().contactTiming()==ContactTiming.EARLY)).hasSize(501);
  assertThat(runs.stream().filter(r->r.result().finalState().contactTiming()==ContactTiming.LATE)).hasSize(225);
  assertThat(runs.stream().filter(r->r.session().randomDrawCount()==0)).hasSize(387);
  assertThat(runs.stream().filter(r->r.session().randomDrawCount()==2)).hasSize(339);
  assertThat(runs.stream().map(r->r.session().randomDrawCount()).collect(Collectors.toSet())).containsExactlyInAnyOrder(0,2);
  assertThat(runs.stream().flatMap(r->r.session().events().stream()).filter(e->e.stage().ordinal()<EpisodeStage.NODE12_CONTACT.ordinal()).map(e->e.publicFacts()+e.stateChanges().toString()+e.causalText()).collect(Collectors.joining(" "))).doesNotContain("NODE12","population=18","waterEmergencyAuthentic");
  assertThat(runs.stream().flatMap(r->r.session().decisions().stream()).filter(ChoiceDecision.class::isInstance).map(ChoiceDecision.class::cast).map(ChoiceDecision::choiceId).collect(Collectors.toSet())).containsExactlyInAnyOrder(ChoiceId.values());
  verifyDoctrineMatrix(runs);verifyCurrentIsPure();verifySample();writeReports(runs);
 }

 @Test void complete2d6MatrixHasNormativeBoundaries(){for(int mod=0;mod<=1;mod++)for(int a=1;a<=6;a++)for(int b=1;b<=6;b++){var check=new FixedDice(a,b).roll(1,0,mod);assertThat(check.total()).isEqualTo(a+b+mod);assertThat(check.returnWindow()).isEqualTo(check.total()<=6?ReturnWindow.SHORT:check.total()<=9?ReturnWindow.NORMAL:ReturnWindow.LONG);}assertThat(new SeededDiceRoller().roll(1703,0,0)).isEqualTo(new SeededDiceRoller().roll(1703,0,0));}

 private List<PathRun> allRuns(){var unique=new LinkedHashMap<String,PathRun>();for(var dice:List.of(new FixedDice(2,3),new FixedDice(3,4),new FixedDice(5,5))){var director=new EpisodeDirector(dice);walk(director,director.start(1703),unique);}return List.copyOf(unique.values());}
 private void walk(EpisodeDirector d,EpisodeSessionState s,Map<String,PathRun> out){var step=d.current(s);assertThat(d.current(s)).isEqualTo(step);if(step.stage()==EpisodeStage.CONSEQUENCE)assertThat(step.choices()).allSatisfy(option->{assertThat(option.price()).isNotBlank().doesNotContain("Состояние изменится по показанной цене");assertThat(option.unknownPart()).isBlank();if(EnumSet.of(ChoiceId.SEND_KROT_FOR_IGLA,ChoiceId.RECOVER_KROT_AND_MODULE,ChoiceId.RESCUE_KROT_WITH_IGLA).contains(option.id()))assertThat(option.risk()).isNotBlank();else assertThat(option.risk()).isBlank();});if(step.terminal()){String key=s.decisions()+"|"+s.world().returnWindow();out.putIfAbsent(key,new PathRun(s,step.result()));return;}if(step.doctrineRequired()){for(var doctrine:Doctrine.all())walk(d,d.decide(s,new DoctrineDecision(doctrine)).session(),out);}else for(var option:step.choices())walk(d,d.decide(s,new ChoiceDecision(option.id())).session(),out);}
 private void verifyDoctrineMatrix(List<PathRun> runs){var expected=Map.of("M>A>R",OutcomeFamily.FULL_MODULE_IGLA_STRANDED,"M>R>A",OutcomeFamily.KROT_AND_MODULE_STRANDED,"A>M>R",OutcomeFamily.DEGRADED_MODULE_ALL_RETURNED,"A>R>M",OutcomeFamily.ALL_RETURNED_MODULE_LOST,"R>M>A",OutcomeFamily.KROT_STRANDED_MODULE_LOST,"R>A>M",OutcomeFamily.KROT_STRANDED_MODULE_LOST);for(var entry:expected.entrySet()){var families=runs.stream().filter(r->r.session().decisions().stream().filter(DoctrineDecision.class::isInstance).map(DoctrineDecision.class::cast).anyMatch(x->x.doctrine().toString().equals(entry.getKey()))).map(r->r.result().finalState().outcomeFamily()).collect(Collectors.toSet());assertThat(families).containsExactly(entry.getValue());}}
 private void verifyCurrentIsPure(){var d=new EpisodeDirector(new FixedDice(2,3));var s=d.start(99);var before=s;var a=d.current(s);var b=d.current(s);assertThat(a).isEqualTo(b);assertThat(s).isEqualTo(before);assertThat(s.randomDrawCount()).isZero();}
 private EpisodeResult sample(){var d=new EpisodeDirector(new SeededDiceRoller());var s=d.start(1703);s=d.decide(s,new ChoiceDecision(ChoiceId.DISCHARGE_BATTERIES)).session();s=d.decide(s,new ChoiceDecision(ChoiceId.START_GREENHOUSE)).session();s=d.decide(s,new DoctrineDecision(Doctrine.of(OrderCard.M,OrderCard.A,OrderCard.R))).session();s=d.decide(s,new ChoiceDecision(ChoiceId.POWER_RESCUE_BEACON)).session();s=d.decide(s,new ChoiceDecision(ChoiceId.SEND_GREENHOUSE_CULTURES)).session();return d.current(s).result();}
 private void verifySample(){var a=sample();var b=sample();assertThat(a).isEqualTo(b);var w=a.finalState();assertThat(a.profile()).isEqualTo(ShelterProfile.AGRARIAN_ALLIANCE);assertThat(w.population()).isEqualTo(45);assertThat(w.foodStatus()).isEqualTo(FoodStatus.RATIONED_TWO_DAYS);assertThat(w.reactorOutput()).isEqualTo(ReactorOutput.LIMITED);assertThat(w.workshopStatus()).isEqualTo(WorkshopStatus.OFFLINE);assertThat(w.allMachinesSaved()).isTrue();assertThat(w.node12Relation()).isEqualTo(Node12Relation.ALLY);assertThat(w.strizh().sensor()).isEqualTo(StrizhSensor.OPERATIONAL);}

 private void writeReports(List<PathRun> runs)throws IOException{Files.createDirectories(REPORTS);var profiles=runs.stream().collect(Collectors.groupingBy(r->r.result().profile(),()->new EnumMap<>(ShelterProfile.class),Collectors.counting()));write("path-summary.md","# Path summary\n\nTerminal paths: **"+runs.size()+"**\n\nDistinct profiles: **"+profiles.size()+"**\n\n"+Arrays.stream(ShelterProfile.values()).map(p->"- `"+p+"`: "+profiles.getOrDefault(p,0L)).collect(Collectors.joining("\n"))+"\n");write("doctrine-matrix.md",doctrineReport());write("director-coverage.md",directorReport(runs));write("risk-matrix.md",riskReport(runs));write("invariant-summary.md","# Invariant summary\n\n- PASS: every terminal path has exactly five player decisions\n- PASS: no dead ends or unknown transitions\n- PASS: resources are non-negative\n- PASS: NODE12 contact occurs exactly once\n- PASS: all seven profiles and all six doctrines are reachable\n- PASS: public pre-contact events contain no NODE12 population or water authenticity\n- PASS: repeated current() is pure\n");write("sample-walkthrough.md",sampleReport(sample()));}
 private String doctrineReport(){var m=Map.of("M>A>R",OutcomeFamily.FULL_MODULE_IGLA_STRANDED,"M>R>A",OutcomeFamily.KROT_AND_MODULE_STRANDED,"A>M>R",OutcomeFamily.DEGRADED_MODULE_ALL_RETURNED,"A>R>M",OutcomeFamily.ALL_RETURNED_MODULE_LOST,"R>M>A",OutcomeFamily.KROT_STRANDED_MODULE_LOST,"R>A>M",OutcomeFamily.KROT_STRANDED_MODULE_LOST);return "# Doctrine matrix\n\n| Doctrine | Outcome family |\n|---|---|\n"+Doctrine.all().stream().map(d->"| `"+d+"` | `"+m.get(d.toString())+"` |").collect(Collectors.joining("\n"))+"\n";}
 private String directorReport(List<PathRun> runs){var timing=runs.stream().collect(Collectors.groupingBy(r->r.result().finalState().contactTiming(),()->new EnumMap<>(ContactTiming.class),Collectors.counting()));return "# Director coverage\n\nNormative sequence: `RESCUE_GATE → NIGHT_PROJECT → DOCTRINE_CRISIS → CONSEQUENCE → NODE12_CONTACT → EPILOGUE`. `REACTOR_ROUTE` resolves atomically after S2.\n\n- EARLY contact paths: "+timing.getOrDefault(ContactTiming.EARLY,0L)+"\n- LATE contact paths: "+timing.getOrDefault(ContactTiming.LATE,0L)+"\n- NODE12 contacts per terminal path: exactly 1\n";}
 private String riskReport(List<PathRun> runs){var sb=new StringBuilder("# 2d6 risk matrix\n\n| d1 | d2 | modifier | total | window |\n|---:|---:|---:|---:|---|\n");for(int mod=0;mod<=1;mod++)for(int a=1;a<=6;a++)for(int b=1;b<=6;b++){int t=a+b+mod;sb.append("| ").append(a).append(" | ").append(b).append(" | +").append(mod).append(" | ").append(t).append(" | `").append(t<=6?"SHORT":t<=9?"NORMAL":"LONG").append("` |\n");}sb.append("\nNo-roll paths (operational sensor): ").append(runs.stream().filter(r->r.session().randomDrawCount()==0).count()).append("\nRolled paths: ").append(runs.stream().filter(r->r.session().randomDrawCount()==2).count()).append("\nReachable modifiers: `0`, `+1`.\n");return sb.toString();}
 private String sampleReport(EpisodeResult r){var w=r.finalState();return "# Sample walkthrough\n\nSeed: `1703`\n\n`DISCHARGE_BATTERIES → START_GREENHOUSE → M>A>R → POWER_RESCUE_BEACON → SEND_GREENHOUSE_CULTURES`\n\n- profile: `"+r.profile()+"`\n- population: "+w.population()+"\n- food: `"+w.foodStatus()+"`\n- reactor: `"+w.reactorOutput()+"`\n- workshop: `"+w.workshopStatus()+"`\n- all machines saved: "+w.allMachinesSaved()+"\n- NODE12: `"+w.node12Relation()+"`\n- STRIZH sensor: `"+w.strizh().sensor()+"`\n\n## Causal chain\n\n```text\n"+r.causalSummary()+"\n```\n";}
 private void write(String name,String text)throws IOException{Files.writeString(REPORTS.resolve(name),text);}
}
