package game.kontur.prototype.domain;

public final class GameTypes {
    private GameTypes() {}
    public enum EpisodeStage { RESCUE_GATE, NIGHT_PROJECT, REACTOR_ROUTE, DOCTRINE_CRISIS, CONSEQUENCE, NODE12_CONTACT, EPILOGUE }
    public enum MachineId { KROT, STRIZH, IGLA }
    public enum SpecialistId { VERA, TIMUR }
    public enum OrderCard { M, A, R }
    public enum MachineLocation { AT_BASE, IN_FIELD, STRANDED, AWAY, LOST }
    public enum MachineLife { OPERATIONAL, DAMAGED, LOST }
    public enum KrotActuator { WORN, DAMAGED, CRIPPLED }
    public enum StrizhSensor { OPERATIONAL, BURNED }
    public enum IglaManipulator { OPERATIONAL, DAMAGED }
    public enum FoodStatus { FOUR_DAYS, THREE_DAYS, SUSTAINABLE, RATIONED_TWO_DAYS }
    public enum PowerMode { FULL, LIMITED, EMERGENCY }
    public enum WorkshopStatus { ONLINE, OFFLINE }
    public enum Node12Relation { UNKNOWN, CONTACTED, COOPERATIVE, ALLY, SILENT }
    public enum ReactorCondition { NONE, FULL, DEGRADED, LOST }
    public enum ReactorLocation { NONE, AT_BASE, STRANDED, INSTALLED, NODE12, LOST }
    public enum ReactorOutput { NONE, FULL, LIMITED }
    public enum ReturnWindow { SHORT, NORMAL, LONG }
    public enum ContactTiming { EARLY, LATE }
    public enum OutcomeFamily { FULL_MODULE_IGLA_STRANDED, KROT_AND_MODULE_STRANDED, DEGRADED_MODULE_ALL_RETURNED, ALL_RETURNED_MODULE_LOST, KROT_STRANDED_MODULE_LOST }
    public enum ShelterProfile { AGRARIAN_ALLIANCE, INDUSTRIAL_HUB, POWERED_STRONGHOLD, MOBILE_COMMUNE, DEPENDENT_NETWORK, AUSTERITY_ENCLAVE, SURVIVAL_OUTPOST }
    public enum WorldFlag { BATTERIES_DISCHARGED, GREENHOUSE_ACTIVE, GENERATOR_PATCHED, PARTS_CONSERVED, RESCUE_BEACON_ACTIVE, TRADE_OFFER_SENT, HELP_REQUEST_SENT, OWES_NODE12, NODE12_IGNORED }
    public enum ChoiceId {
        BREAK_GATE, TECH_CHANNEL_VERA, TECH_CHANNEL_TIMUR, DISCHARGE_BATTERIES,
        START_GREENHOUSE, PATCH_GENERATOR, REPAIR_STRIZH_SENSOR, REPAIR_KROT_ACTUATOR, CONSERVE_PARTS,
        INSTALL_FULL_POWER, POWER_RESCUE_BEACON, SEND_KROT_FOR_IGLA,
        RECOVER_KROT_AND_MODULE, RECOVER_MODULE_ONLY, ABANDON_REACTOR_SITE,
        INSTALL_LIMITED_MODULE, DISASSEMBLE_MODULE, OFFER_MODULE_FOR_TRADE,
        ACCEPT_AUSTERITY, CANNIBALIZE_KROT, BROADCAST_FOR_HELP,
        RESCUE_KROT_WITH_IGLA, ABANDON_KROT, REQUEST_EXTERNAL_RESCUE,
        SEND_GREENHOUSE_CULTURES, SHARE_REACTOR_POWER, TRADE_DEGRADED_MODULE, SEND_IGLA_TO_NODE12, IGNORE_NODE12
    }
}
