package game.kontur.prototype.cli;

import java.util.*;
import game.kontur.prototype.domain.Doctrine;
import game.kontur.prototype.domain.EpisodeModels.*;
import game.kontur.prototype.episode.EpisodeDirector;
import static game.kontur.prototype.domain.GameTypes.OrderCard;

public final class Main {
 private Main(){}
 public static void main(String[] args){long seed=parseSeed(args);var in=new Scanner(System.in);var director=new EpisodeDirector();var session=director.start(seed);System.out.println("КОНТУР v0.3 — Кислотный фронт\nSeed: "+seed);while(true){var step=director.current(session);System.out.println("\n== "+step.title()+" ==\n"+step.briefing());if(step.terminal()){printResult(step.result());System.out.print("Показать причинную цепочку? [y/N]: ");if(in.hasNextLine()&&in.nextLine().trim().equalsIgnoreCase("y"))System.out.println(localize(step.result().causalSummary()));return;}if(step.doctrineRequired()){System.out.print("Введите доктрину (например M>A>R): ");session=director.decide(session,new DoctrineDecision(parseDoctrine(in.nextLine()))).session();}else{for(int i=0;i<step.choices().size();i++){var o=step.choices().get(i);System.out.printf("%d. %s — %s%n",i+1,o.intent(),localize(o.price()));}int n=readChoice(in,step.choices().size());session=director.decide(session,new ChoiceDecision(step.choices().get(n-1).id())).session();}}}
 private static int readChoice(Scanner in,int max){while(true){System.out.print("Ваш выбор: ");if(!in.hasNextLine())throw new IllegalStateException("Консольный ввод закрыт");try{int n=Integer.parseInt(in.nextLine().trim());if(n>=1&&n<=max)return n;}catch(NumberFormatException ignored){}System.out.println("Введите число от 1 до "+max+".");}}
 private static Doctrine parseDoctrine(String value){var p=Arrays.stream(value.trim().toUpperCase(Locale.ROOT).split(">" )).map(String::trim).map(OrderCard::valueOf).toArray(OrderCard[]::new);return Doctrine.of(p);}
 private static long parseSeed(String[] args){for(int i=0;i<args.length;i++){if(args[i].equals("--seed")&&i+1<args.length)return Long.parseLong(args[i+1]);if(args[i].startsWith("--seed="))return Long.parseLong(args[i].substring(7));}return 1703L;}
 private static void printResult(EpisodeResult r){var w=r.finalState();System.out.println(r.atmosphericSummary());System.out.println("\nИтог: профиль — "+localize(r.profile().name())+", население — "+w.population()+", пища — "+localize(w.foodStatus().name())+", энергия — "+localize(w.powerMode().name())+", мастерская — "+localize(w.workshopStatus().name())+", реактор — "+localize(w.reactorOutput().name())+", Узел-12 — "+localize(w.node12Relation().name()));System.out.println("KROT: "+localize(w.krot().life().name())+", "+localize(w.krot().location().name())+", привод "+localize(w.krot().actuator().name())+"\nSTRIZH: "+localize(w.strizh().life().name())+", "+localize(w.strizh().location().name())+", сенсор "+localize(w.strizh().sensor().name())+"\nIGLA: "+localize(w.igla().life().name())+", "+localize(w.igla().location().name())+", манипулятор "+localize(w.igla().manipulator().name()));System.out.println("Решения: "+r.decisions().stream().map(Main::decisionText).toList()+"; seed="+r.seed());}
 private static String decisionText(PlayerDecision d){return d instanceof DoctrineDecision x?x.doctrine().toString():choiceText(((ChoiceDecision)d).choiceId());}
 private static String choiceText(game.kontur.prototype.domain.GameTypes.ChoiceId id){return switch(id){case BREAK_GATE->"сломать шлюз";case TECH_CHANNEL_VERA->"вывести Веру";case TECH_CHANNEL_TIMUR->"вывести Тимура";case DISCHARGE_BATTERIES->"разрядить батареи";case START_GREENHOUSE->"запустить теплицу";case PATCH_GENERATOR->"залатать генератор";case REPAIR_STRIZH_SENSOR->"починить сенсор STRIZH";case REPAIR_KROT_ACTUATOR->"починить привод KROT";case CONSERVE_PARTS->"сберечь детали";case INSTALL_FULL_POWER->"запустить полную мощность";case POWER_RESCUE_BEACON->"питать спасательный маяк";case SEND_KROT_FOR_IGLA->"отправить KROT за IGLA";case RECOVER_KROT_AND_MODULE->"вернуть KROT и модуль";case RECOVER_MODULE_ONLY->"вернуть модуль";case ABANDON_REACTOR_SITE->"оставить реакторный сектор";case INSTALL_LIMITED_MODULE->"установить ограниченный модуль";case DISASSEMBLE_MODULE->"разобрать модуль";case OFFER_MODULE_FOR_TRADE->"предложить модуль для обмена";case ACCEPT_AUSTERITY->"принять экономию";case CANNIBALIZE_KROT->"разобрать KROT";case BROADCAST_FOR_HELP->"просить о помощи";case RESCUE_KROT_WITH_IGLA->"спасти KROT с IGLA";case ABANDON_KROT->"оставить KROT";case REQUEST_EXTERNAL_RESCUE->"запросить эвакуацию";case SEND_GREENHOUSE_CULTURES->"передать культуры";case SHARE_REACTOR_POWER->"поделиться энергией";case TRADE_DEGRADED_MODULE->"обменять модуль";case SEND_IGLA_TO_NODE12->"отправить IGLA в Узел-12";case IGNORE_NODE12->"игнорировать Узел-12";};}
 private static String localize(String text){
  var result=text;
  for(var id:game.kontur.prototype.domain.GameTypes.ChoiceId.values())result=result.replace(id.name(),choiceText(id));
  result=result.replace("NODE12","Узел-12").replace("SHORT","короткое").replace("NORMAL","обычное").replace("LONG","длинное").replace("EARLY","ранний").replace("LATE","поздний");
  return result.replace("FULL_MODULE_IGLA_STRANDED","полный модуль, IGLA оставлена").replace("KROT_AND_MODULE_STRANDED","KROT и модуль оставлены").replace("DEGRADED_MODULE_ALL_RETURNED","повреждённый модуль, все вернулись").replace("ALL_RETURNED_MODULE_LOST","все вернулись, модуль потерян").replace("KROT_STRANDED_MODULE_LOST","KROT оставлен, модуль потерян").replace("matched=true","сработал").replace("matched=false","не сработал").replace("AGRARIAN_ALLIANCE","аграрный союз").replace("INDUSTRIAL_HUB","промышленный узел").replace("POWERED_STRONGHOLD","энергетическая крепость").replace("MOBILE_COMMUNE","мобильная коммуна").replace("DEPENDENT_NETWORK","зависимая сеть").replace("AUSTERITY_ENCLAVE","анклав экономии").replace("SURVIVAL_OUTPOST","форпост выживания").replace("RATIONED_TWO_DAYS","паёк на два дня").replace("SUSTAINABLE","устойчивая").replace("THREE_DAYS","на три дня").replace("FOUR_DAYS","на четыре дня").replace("OPERATIONAL","исправен").replace("DAMAGED","повреждён").replace("BURNED","сгорел").replace("WORN","изношен").replace("CRIPPLED","неработоспособен").replace("AT_BASE","на базе").replace("AWAY","в пути").replace("STRANDED","оставлен").replace("LOST","потерян").replace("LIMITED","ограниченная").replace("EMERGENCY","аварийная").replace("FULL","полная").replace("OFFLINE","отключена").replace("ONLINE","работает").replace("ALLY","союз").replace("COOPERATIVE","сотрудничество").replace("SILENT","молчание").replace("UNKNOWN","неизвестно");
 }
}
