import { PACKETS, RISK_CASES, scenarioVersion, contentVersion, advanceSession, isTerminal } from "./scenario.js";

const KEY = "kontur-narrative-v04-runner";
const root = document.querySelector("#app");
const questions = ["Где находились КОНТУР, группа, Аша и кассета в ключевой сцене?", "Что такое кассета и почему она была важна?", "Какой выбор был самым трудным и почему?", "Каков был риск маршрута и что означал результат кубиков?", "Хотелось бы увидеть следующий день именно этого мира?", "Это ощущалось историей или меню ресурсов?"];
const DEBRIEF = "«Пара двух шестигранных кубиков в этой сессии была назначена до начала прохождения. Так три небольшие тестовые сессии покрывают осложнение, успех с ценой и преимущество. Это способ проверки сценария, а не правило будущей игры».";
const queryCase = new URLSearchParams(location.search).get("case")?.toUpperCase();

function randomCase() { const list=["LOW","MID","HIGH"]; return list[crypto.getRandomValues(new Uint32Array(1))[0] % list.length]; }
function load() { try { return JSON.parse(sessionStorage.getItem(KEY)); } catch { return null; } }
function save(state) { sessionStorage.setItem(KEY, JSON.stringify(state)); }
function el(tag, text, className) { const node=document.createElement(tag); if(text) node.textContent=text; if(className) node.className=className; return node; }
function resetView() { root.replaceChildren(); root.focus(); }
function start() { const forced=["LOW","MID","HIGH"].includes(queryCase) ? queryCase : null; save({ startedAt:new Date().toISOString(), riskCase:forced ?? randomCase(), packetId:"NRV04-P01", history:[], restarted:Boolean(load()), answers:{} }); render(); }
function current() { return load(); }
function choose(choiceId, buttons) { const state=current(); if(!state || isTerminal(state.packetId)) return; buttons.forEach((button)=>button.disabled=true); const next=advanceSession(state, choiceId); save({ ...next, startedAt:state.startedAt, restarted:state.restarted, answers:state.answers }); render(); }
function renderStart() { resetView(); const box=el("section",null,"panel"); box.append(el("h1","КОНТУР — Тихий резервуар"),el("p","Автономный исследовательский сценарий. Это не production-игра."),el("p","Тест занимает до 15–30 минут. Данные никуда автоматически не отправляются.","notice")); const button=el("button","Я согласен(на) и хочу начать","primary"); button.addEventListener("click",start); box.append(button); root.append(box); }
function render() { const state=current(); if(!state) return renderStart(); if(isTerminal(state.packetId)){ if(state.reportShown) return renderReport(state); if(state.debriefShown) return renderDebrief(state); return renderTerminal(state); } resetView(); const data=PACKETS[state.packetId]; root.append(el("div",data.water,"panel water")); const scene=el("article",null,"panel"); scene.append(el("h1","Тихий резервуар"),el("h2", data.scene === "PRESSURE_SHAFT" ? "Результат и следующий выбор" : "Текущая сцена")); scene.append(el("pre",data.map)); data.body.forEach((line)=>scene.append(el("p",line))); const choices=el("div",null,"choices"), buttons=[]; data.choices.forEach((item,index)=>{ const b=el("button",`${index+1}. ${item.label} — ${item.consequence}`); b.addEventListener("click",()=>choose(item.id,buttons)); buttons.push(b); choices.append(b); }); scene.append(choices); root.append(scene); }
function answersComplete(state) { return questions.every((_,index)=>Boolean(state.answers[index]?.trim())); }
function report(state) { if(!answersComplete(state) || !state.reportShown) throw new Error("Отчёт доступен только после шести ответов и debrief"); const risk=RISK_CASES[state.riskCase]; const end=state.endedAt; const duration=Math.round((Date.parse(end)-Date.parse(state.startedAt))/1000); return ["КОНТУР — Тихий резервуар: локальный отчёт",`scenarioVersion: ${scenarioVersion}`,`contentVersion: ${contentVersion}`,`riskCase: ${state.riskCase} (${risk.label})`,"фактические кубики: "+risk.dice.join(" + "),`время начала: ${state.startedAt}`,`время окончания: ${end}`,`длительность секунд: ${duration}`,"решения:",...state.history.map((h,i)=>`${i+1}. ${h.label}`),"служебный путь:",...state.history.map((h)=>`${h.packetId} + ${h.choiceId}`),`terminal packet: ${state.packetId}`,"ответы:",...questions.map((q,i)=>`${i+1}. ${q}\n${state.answers[i]}`),`userAgent: ${navigator.userAgent}`,`перезапуск сессии: ${state.restarted ? "да" : "нет"}`].join("\n"); }
function renderTerminal(state) { if(!state.endedAt){ save({...state,endedAt:new Date().toISOString()}); state=current(); } resetView(); const data=PACKETS[state.packetId], box=el("article",null,"panel"), areas=[]; box.append(el("div",data.water,"panel water"),el("h1","Итог"),el("pre",data.map)); data.body.forEach((line)=>box.append(el("p",line))); box.append(el("h2","Вопросы после прохождения")); questions.forEach((q,i)=>{ const label=el("label",`${i+1}. ${q}`); label.htmlFor=`answer-${i}`; const area=document.createElement("textarea"); area.id=`answer-${i}`; area.value=state.answers[i]??""; area.addEventListener("input",()=>{const latest=current(); latest.answers[i]=area.value; save(latest);}); areas.push(area); box.append(label,area); }); const error=el("p","Ответьте на все шесть вопросов, чтобы перейти к debrief.","notice"); error.id="answers-error"; error.setAttribute("role","alert"); error.hidden=true; areas.forEach((area)=>area.setAttribute("aria-describedby",error.id)); const actions=el("div",null,"choices"); const make=el("button","Завершить ответы","primary"); make.addEventListener("click",()=>{ const latest=current(); const emptyIndex=questions.findIndex((_,index)=>!latest.answers[index]?.trim()); if(emptyIndex>=0){ error.hidden=false; areas[emptyIndex].focus(); return; } save({...latest,debriefShown:true}); renderDebrief(current()); }); const again=el("button","Начать заново","danger"); again.addEventListener("click",()=>{ if(confirm("Текущая сессия будет заменена. Продолжить?")) start(); }); actions.append(make,again); box.append(error,actions); root.append(box); }
function renderDebrief(state) { resetView(); const box=el("section",null,"panel"); box.append(el("h1","Debrief"),el("p",DEBRIEF,"notice")); const actions=el("div",null,"choices"); const show=el("button","Показать отчёт","primary"); show.addEventListener("click",()=>{ const latest=current(); save({...latest,reportShown:true}); renderReport(current()); }); actions.append(show); box.append(actions); root.append(box); }
function renderReport(state) { resetView(); const text=report(state), box=el("section",null,"panel"); box.append(el("h1","Локальный отчёт"),el("p","Отчёт существует только в этом браузере, пока вы сами не скопируете или не скачаете его.","notice"),el("pre",text,"report")); const actions=el("div",null,"choices"); const copy=el("button","Скопировать отчёт","primary"); copy.addEventListener("click",async()=>{await navigator.clipboard.writeText(text); copy.textContent="Отчёт скопирован";}); const download=el("button","Скачать отчёт .txt"); download.addEventListener("click",()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type:"text/plain;charset=utf-8"}));a.download="kontur-tihiy-rezervuar-report.txt";a.click();URL.revokeObjectURL(a.href);}); const again=el("button","Начать заново","danger"); again.addEventListener("click",()=>{if(confirm("Текущая сессия будет заменена. Продолжить?")) start();}); actions.append(copy,download,again); box.append(actions); root.append(box); }
render();
